[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
merkle_tree = { path = "../merkle_tree" }
simple_database = { path = "../simple_database" }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"