[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
merkle_tree = { path = "../merkle_tree" }
simple_database = { path = "../simple_database" }
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
file = "1.0.0"
