[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
merkle_tree = { path = "../merkle_tree" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"