[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = {version="0.2.0", features=["alloc"]}
sha2 = "0.10"
serde = "1.0"
serde_derive = "1.0"
